CocoPalace/CocoPalace/urls.py
from django.contrib import admin
from django.urls import path, include
from CocoPalaceapp.urls import urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('test/', include("CocoPalaceapp.urls")),
]

CocoPalace/CocoPalaceapp/urls.py
from django.urls import path
from . import views


app_name = "test"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote")
]

CocoPalace/CocoPalaceapp/models.py
from email.policy import default
from django.db import models
from django.utils import timezone
import datetime

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date= models.DateTimeField("date published")

    def __str__(self):
        return self.question_text

    def was_publish_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

CocoPalace/CocoPalaceapp/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from .models import Choice, Question
from django.views import generic


## Class views

class IndexView(generic.ListView):
    template_name = "questions/index.html"
    context_object_name = "question_list"

    def get_queryset(self):
        """ Retunr last five questions """
        return Question.objects.order_by("-pub_date")[:5]

class DetailView(generic.DeleteView):
    model = Question
    template_name = "questions/detail.html"
    context_object_name = "question"
    
class ResultView(generic.DeleteView):
    model = Question
    template_name = "questions/results.html"
    context_object_name = "question"

## Function Views

# def index(request):
#     lastes_question_list = Question.objects.all()
#     return render(request, "questions/index.html", {
#         "question_list": lastes_question_list
#     })

# def detail(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, "questions/detail.html", {
#         "question": question
#     })

# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, "questions/results.html", {
#         "question": question
#     })

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        return render(request, "questions/detail.html", {
            "question" : question,
            "error_message": "Ups... error saving the answer"
        })
    else: 
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse("test:results", args=[question.id]))

CocoPalace/CocoPalaceapp/templates/questions/detail.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title> Question Detail </title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    </head>
    <body>
        <nav class="navbar bg-dark">
            <div class="container">
                <a class="navbar-brand" href="{% url 'test:index'%}">
                    <h1 style="color: #fff;"> Django test </h1>
                </a>
            </div>
        </nav>
        <br>
        <main class="container">
            <form action="{% url 'test:vote' question.id %}" method="POST">
                {% csrf_token %}
                <fieldset>
                    <legend>
                        <h2>{{ question.question_text }}</h2>
                    </legend>
                    {% if error_message %}
                        <div class="alert alert-danger" role="alert">
                            {{ error_message }}
                        </div>
                    {% endif %}
                    <ul class="list-group">
                        {% for choice in question.choice_set.all %}
                        <li class="list-group-item">
                            <input
                                class="form-check-input"
                                type="radio" 
                                name="choice" 
                                id="choice{{ forloop.counter }}"
                                value="{{choice.id}}"
                            />
                            <label class="form-check-label" for="choice{{ forloop.counter }}">
                                {{ choice.choice_text }}
                            </label>
                        </li>    
                        {% endfor %}
                    </ul>
                </fieldset>
                <br>
                <input class="btn btn-success" type="submit" value="Vote" />
            </form>
        </main>
    </body>
</html>

CocoPalace/CocoPalaceapp/templates/questions/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title> Question List </title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    </head>
    <body>
        <nav class="navbar bg-dark">
            <div class="container">
                <a class="navbar-brand" href="{% url 'test:index'%}">
                    <h1 style="color: #fff;"> Django test </h1>
                </a>
            </div>
        </nav>
        <br>
        <main class="container">
            {% if question_list %}
                <ul class="list-group">
                    {% for question in question_list %}
                    <li class="list-group-item">
                        <a href="{% url 'test:detail' question.id %}">
                            {{ question.question_text }}
                        </a>
                    </li>
                    {% endfor %}
                </ul>
            {% endif %}
        </main>
        
    </body>
</html>

CocoPalace/CocoPalaceapp/templates/questions/results.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title> Results of question </title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    
    </head>
    <body>
        <nav class="navbar bg-dark">
            <div class="container">
                <a class="navbar-brand" href="{% url 'test:index'%}">
                    <h1 style="color: #fff;"> Django test </h1>
                </a>
            </div>
        </nav>
        <br>
        <main class="container">
            <h2> {{ question.question_text }} </h2>
            <ul>
                {% for choice in question.choice_set.all %}
                    <li>
                        {{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}
                    </li>
                {% endfor %}
            </ul>
            <div class="row p-4">
                <div class="col-6 p-2">
                    <a class="btn btn-primary" href="{% url 'test:detail' question.id %}"> Vote again </a>
                </div>
                <div class="col-6 p-2">
                    <a class="btn btn-success" href="{% url 'test:index'%}"> Return to list</a>
                </div>
            </div>
        </main>
    </body>
</html>